spring:
  cloud:
    gcp:
      project-id: pilotopubsub
      credentials:
        location: classpath:pilotopubsub-447a8cb5740c.json

service:
  cadastro-usuario:
    url: http://localhost:8082/v1/users

